apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edmo120
  description: Backstage component for edmo120
  annotations:
    dependencytrack/project-id: "b03fc3d4-0b3e-4675-b062-4a8b33052133"
    iap/app-info: "1/63636ee9-2f7b-4d68-9de3-b701436c8e4c"
    github.com/project-slug: Miracle-6785/final-demo2
    jenkins.io/job-full-name: edmo120-org/edmo120-job
    sonarqube.org/project-key: default/edmo120
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/register-new-application
spec:
  type: service
  lifecycle: production
  owner: user:guest
