apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "final-demo2"
  description: "A component that is part of the DevSecOps catalog"
  annotations:
    
    jenkins.io/job-full-name: final-demo2-org/final-demo2-job
    

    
    sonarqube.org/project-key: default/final-demo2
    

    dependencytrack/project-id: "9c098ced-8181-4faf-b122-9e126db64ce4"
    iap/app-info: "1/7a1c8ece-1fa3-4205-a501-e3d1e26cbf00"
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: user:guest
  lifecycle: experimental
