apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  description: Backstage component for hello
  annotations:
    github.com/project-slug: Miracle-6785/final-demo2
    jenkins.io/job-full-name: hello-org/hello-job
    sonarqube.org/project-key: default/hello
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/register-new-application
spec:
  type: service
  lifecycle: production
  owner: user:guest
