apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Miraclefff
  description: Backstage component for Miraclefff
  annotations:
    github.com/project-slug: Miracle-6785/final-demo2
    jenkins.io/job-full-name: Miraclefff-org/Miraclefff-job
    sonarqube.org/project-key: default/Miraclefff
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/register-new-application
spec:
  type: service
  lifecycle: production
  owner: user:guest
